---
# Redhat based OS
- name: mariadb | Install MariaDB role and setup
  include_role:
    name: joe-speedboat.mariadb
  vars:
    mariadb_secure_installation: yes
    mariadb_databases:
      - name: '{{ mariadb_db_name }}'
    mariadb_users_create:
      - name: '{{ mariadb_db_user }}'
        hosts: 
        - '{{ mariadb_db_host }}'
        password: "{{ mariadb_user_password }}"
        privs:
        - "{{ mariadb_db_name }}.*:ALL"
        append_privs: no

- name: Create Rundeck Repo
  template:
    src: rundeck.repo.j2
    dest: /etc/yum.repos.d/rundeck.repo
    owner: root
    group: root
    mode: 0644

- name: rundeck | install packages
  dnf:
    name: "{{ rundeck_packages_EL }}"
    state: present
  notify:
    - start rundeck
...
