---
# Redhat based OS
- name: mariadb | Install MariaDB role and setup
  include_role:
    name: joe-speedboat.mariadb
  vars:
    mariadb_secure_installation: yes
    mariadb_databases:
      - name: '{{ mariadb_db_name }}'
    mariadb_users_create:
      - name: '{{ mariadb_db_user }}'
        hosts:
        - '{{ mariadb_db_host }}'
        password: "{{ mariadb_user_password }}"
        privs:
        - "{{ mariadb_db_name }}.*:ALL"
        append_privs: no

- name: rundeck | install repos
  dnf: 
    name: "{{ rundeck_repos_EL8 }}"
    state: present
    disable_gpg_check: True

- name: fetch Rundeck community repo setup script
  get_url: 
    url: "{{ rundeck_repo_setup_script_EL8 }}"
    dest: /tmp/setup_rundeck_repo.sh
    mode: 0700

- name: Execute repo installer
  shell: /tmp/setup_rundeck_repo.sh rundeck

- name: Remove the repo installer
  file: 
    path: /tmp/setup_rundeck_repo.sh
    state: absent

- name: rundeck | install packages
  dnf:
    name: "{{ rundeck_packages_EL8 }}"
    state: present
  notify:
    - start rundeck
...
