---
#  create groups and adjust user
- name: rundeck | ensure home directory has correct permissions
  file:
    path: /var/lib/rundeck
    state: directory
    owner: rundeck
    group: rundeck
    mode: 0755

- name: rundeck | ensure tmp directory has correct permissions
  file:
    path: /tmp/rundeck
    state: directory
    owner: rundeck
    mode: 0755

- name: rundeck | ensure server url is configured (rundeck-config.properties)
  lineinfile:
    dest: /etc/rundeck/rundeck-config.properties
    regexp: '^grails.serverURL='
    line: 'grails.serverURL={{ rundeck_protocol }}://{{ rundeck_domain }}'
  notify:
    - restart rundeck

- name: rundeck | ensure server url is configured (rundeck-config.properties)
  lineinfile:
    dest: /etc/rundeck/rundeck-config.properties
    regexp: '^server.useForwardHeaders='
    line: 'server.useForwardHeaders=true'
  notify:
    - restart rundeck

- name: rundeck | ensure server url is configured (framework.properties)
  lineinfile:
    dest: /etc/rundeck/framework.properties
    regexp: '^framework\.server\.url\s*\=s*'
    line: 'framework.server.url = {{ rundeck_protocol }}://{{ rundeck_domain }}'
  notify:
    - restart rundeck

- name: rundeck | download rundeck plugins
  get_url:
    dest: /var/lib/rundeck/libext/{{ item.split('/')|last }}
    url: '{{ item }}'
  with_items: '{{ rundeck_plugins }}'
  when: rundeck_plugins is iterable
  notify:
    - restart rundeck
