- name: "Rundeck | update basic security to have users"
  lineinfile:
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:.*"
    line: "admin: MD5:{{ rundeck_admin_pass | hash('md5') }},user,admin,architect,deploy,build"
    state: present
  notify:
    - restart rundeck

- name: Rundeck | remove default admin user
  lineinfile:
    backup: yes
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:admin,.*"
    state: absent
  notify:
    - restart rundeck
