---
- name: ansible | fetch install script
  ansible.builtin.get_url:
    url: "{{ rundeck_ansible_installer_url }}"
    dest: "{{ rundeck_ansible_installer_path }}"
    owner: root
    group: root
    mode: "0700"

- name: ansible | execute the installer
  ansible.builtin.command: "sh {{ rundeck_ansible_installer_path }}"
  args:
    creates: "{{ rundeck_ansible_uv_marker }}"

...
