---
- name: ansible | fetch install script
  get_url: 
    url: https://raw.githubusercontent.com/joe-speedboat/ansible.template/master/tests/ansible_setup_local.sh
    dest: /usr/local/sbin/ansible_setup_local.sh
    mode: 700
    
- name: ansible | execute the installer
  shell: /usr/local/sbin/ansible_setup_local.sh

- name: ansible | remove the installer
  file: 
    path: ansible | remove the Ansible Installer
    state: absent

- name: ansible | prepare /etc/ansible for rundeck user
  file: 
    dest: /etc/ansible
    owner: rundeck 
    group: rundeck 
    mode: u=rwX,g=rwX,o-rwX 
    recurse: yes
...
