---
- name: rundeck | install base software
  include_tasks: 10_install.yml

- name: rundeck | configure config files
  include_tasks: 20_configure.yml

- name: rundeck | configure rundeck mariadb client
  include_tasks: 30_mysql_client.yml

- name: rundeck | user management
  include_tasks: 40_users.yml

- name: rundeck | ssh key generation for rundeck user
  include_tasks: 50_ssh.yml
  when: rundeck_generate_ssh

- name: rundeck | install and configure nginx reverse proxy
  include_tasks: 60_nginx.yml
