- name: Rundeck | encode users password
  shell: "echo -n {{ rundeck_admin_pass }} | md5sum | cut -d' '  -f1"
  become: True
  register: rundeck_encoded_admin_pass
# - debug: var=rundeck_encoded_admin_pass

- name: "Rundeck | update basic security to have users"
  lineinfile:
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:.*"
    line: "admin: MD5:{{ rundeck_encoded_admin_pass.stdout }},user,admin,architect,deploy,build"
    state: present
  notify:
    - restart rundeck

- name: Rundeck | remove default admin user
  lineinfile:
    backup: yes
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:admin,.*"
    state: absent
  notify:
    - restart rundeck
