---
- name: start rundeck
  systemd: 
    name: rundeckd 
    state: started 
    enabled: true

- name: restart rundeck
  service: 
    name: rundeckd 
    state: restarted 
    enabled: true

- name: restart nginx
  service: 
    name: nginx 
    state: restarted 
    enabled: true
